name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm ci
      - run: npm run lint
